Improve/remove identity
Zigalow/Todo-app_Csharp-Application pull request #12
Opened 2024-11-20 00:06 UTC by ZeeDiazz

Removed Identity from all Account pages and implemented Userservice to communicate with Api.
In API I have implemented a UserController.

2024-11-20 21:19 UTC, Zigalow requested changes
Det ser okay ud men jeg skrevet kommentarer til det jeg lige vil have du kigger på igen.

Generelt er der to ting:

## Endpoints og UserInfo Dto
Jeg tror det giver bedst mening, enten at lave en dto til hvert endpoint, eller lave et endpoint, der opdaterer flere af tingene på en gang.
Du kan tjekke kommentaren i UserInfo filen

## Nullable properties i dtos
Der forekommer nullable attributter i nogle af dine dtos. Mener det betyder at det ikke er nødvendigt at udfylde. Er det meningen det skal være sådan?

2024-11-20 21:19 UTC, Zigalow commented on Todo.Core/Dtos/AuthDto/PasswordDto.cs
> +    public string? NewPassword { get; set; } = String.Empty;
Burde de ikke være non-nullable?

2024-11-20 21:19 UTC, Zigalow commented on Todo.Core/Dtos/AuthDto/UserInfoDto.cs
Det ligner lidt at du bruger de forskellige properties i denne dto til hver deres endpoint, i stedet for at have en dto til hver endpoint.


Så, i stedet for at have en updateUserNameDto, updateEmailDto, så har du denne i stedet.

Jeg tror det giver bedst mening, enten at lave en dto til hvert endpoint, eller lave et endpoint, der opdaterer flere af tingene på en gang.

Så i stedet for at have en UpdateEmail og en UpdatePhoneNumber, så har du bare et endpoint der hedder UpdateUserInfo

2024-11-20 21:19 UTC, Zigalow commented on Todo.Web/Auth/IUserService.cs
Se kommentaren til UserInfo filen

2024-11-20 21:19 UTC, Zigalow commented on Todo.Web/Auth/Models/ChangePasswordRequest.cs
Burde de ikke være non-nullable?

2024-11-20 21:19 UTC, Zigalow commented on Todo.Web/wwwroot/js/qrcode.min.js
okay...

2024-11-20 21:19 UTC, Zigalow commented on Todo.Api/Controllers/UserController.cs
Du burde nok have noget check for modelstate. Ved ikke om det er MEGET relevant, men det er nok godt at have med:


```
    if (!ModelState.IsValid)
        {
            return BadRequest(ModelState);
        }
```

2024-11-20 21:19 UTC, Zigalow commented on Todo.Api/Controllers/UserController.cs
>  public class UserController: ControllerBase
Du mangler også ```[Authorize]``` tag.
Lige nu kan man requeste selvom man ikke er authorized

2024-11-23 15:51 UTC, ZeeDiazz commented on Todo.Api/Controllers/UserController.cs
>  public class UserController: ControllerBase
Added [Authorize] tag

2024-11-23 15:51 UTC, ZeeDiazz commented on Todo.Api/Controllers/UserController.cs
added check for mdoelstate in each method

2024-11-23 15:52 UTC, ZeeDiazz commented on Todo.Web/Auth/Models/ChangePasswordRequest.cs
Du har ret! dette er fixed

2024-11-23 15:52 UTC, ZeeDiazz commented on Todo.Web/Auth/IUserService.cs
har tilføjede flere dto'er

2024-11-23 15:53 UTC, ZeeDiazz commented on Todo.Core/Dtos/AuthDto/UserInfoDto.cs
har lavet flere dto'er i stedet for UserInfo

2024-11-23 15:53 UTC, ZeeDiazz commented on Todo.Core/Dtos/AuthDto/PasswordDto.cs
> +    public string? NewPassword { get; set; } = String.Empty;
That is correct! har fixed det

2024-11-23 17:57 UTC, Zigalow requested changes
Kun valideringstjek tilbage. Ellers ser det fint ud

2024-11-23 17:57 UTC, Zigalow commented on Todo.Core/Dtos/UserInfoDtos/AddPasswordDto.cs
Burde nok være check så man sikrer at passwordet overholder kravene

2024-11-23 17:57 UTC, Zigalow commented on Todo.Core/Dtos/UserInfoDtos/ChangePasswordDto.cs
Burde nok være check så man sikrer at passwordet overholder kravene

2024-11-23 17:57 UTC, Zigalow commented on Todo.Core/Dtos/UserInfoDtos/UpdateEmailDto.cs
Burde nok være check så man sikrer at email overholder kravene

2024-11-23 17:57 UTC, Zigalow commented on Todo.Core/Dtos/UserInfoDtos/UpdatePhoneNumberDto.cs
Burde nok være check så man sikrer at telefonnumeret er af tal f.eks.
Burde måske være af typen int i dto'en og så kan det konverteres bagefter

2024-11-23 18:58 UTC, ZeeDiazz commented on Todo.Core/Dtos/UserInfoDtos/UpdatePhoneNumberDto.cs
der er validation i frontenden, den viser en error bedsked med at det skal være tal. Men har også lige tilføjet telefone nummers længde.

2024-11-24 20:25 UTC, merged