Drag drop task
Zigalow/Todo-app_Csharp-Application pull request #13
Opened 2024-11-20 14:00 UTC by ZeeDiazz

Implemented drag and drop for TodoItems, you can now move TodoItems between the different todoLists

2024-11-20 21:43 UTC, Zigalow requested changes
Mangler reordering. 

Syntes også UI'en er ret underlig. Der kommer sådan et kæmpe X når jeg prøver at add en task. Det skal desværre fikses før pr accepteres


Ellers er det fint

2024-11-20 21:43 UTC, Zigalow commented on Todo.Api/Controllers/TodoItemsController.cs
Fint. Kan ikke se dit reorder todoItem endpoint

2024-11-20 21:43 UTC, Zigalow commented on Todo.Web/Services/interfaces/ITodoItemService.cs
> +    Task<bool> ReorderTodoItemAsync(int todoItemId, int newIndex);
Den er vist ikke færdigimplementeret? Tænker det giver bedst mening at færdiggøre denne feature eller afkaste den, inden pr accepteres

2024-11-23 16:18 UTC, ZeeDiazz commented
> Mangler reordering.
> 
> Syntes også UI'en er ret underlig. Der kommer sådan et kæmpe X når jeg prøver at add en task. Det skal desværre fikses før pr accepteres
> 
Har prøvet i forskellige browsers (Chrome og Brave), har også prøvet at reload min cache og der kommer en en Kæmpe X
![image](https://github.com/user-attachments/assets/d304b49c-955d-4a68-91c0-c6c7e0428390)

2024-11-23 18:06 UTC, Zigalow commented
> > Mangler reordering.
> > Syntes også UI'en er ret underlig. Der kommer sådan et kæmpe X når jeg prøver at add en task. Det skal desværre fikses før pr accepteres
> 
> Har prøvet i forskellige browsers (Chrome og Brave), har også prøvet at reload min cache og der kommer en en Kæmpe X ![image](https://private-user-images.githubusercontent.com/69626255/389210350-d304b49c-955d-4a68-91c0-c6c7e0428390.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzODUwMTcsIm5iZiI6MTczMjM4NDcxNywicGF0aCI6Ii82OTYyNjI1NS8zODkyMTAzNTAtZDMwNGI0OWMtOTU1ZC00YTY4LTkxYzAtYzZjN2UwNDI4MzkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDE3NTgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3MzVkNDk3ZWQ4MDBjMWQ4YzY5NzE5OTM4NTE0ZDEyMTNmNDczZDc4YmQ3YTRiZGM5NDdhMGJhOTgzZTRiZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qNoKqsz9k-sCPlSDbx8KxSWRBGAVJ75TRZ59CcpgxMA)

2024-11-23 18:07 UTC, Zigalow commented
Får heller ikke det store x i inkognito tilstand.

Du kan bare merge

2024-11-23 18:07 UTC, Zigalow approved these changes

2024-11-23 18:08 UTC, Zigalow commented
Vi skal bare lige huske at fikse css'en med labels i vores fælles branch

2024-11-23 18:39 UTC, merged